// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateTab(arg1) {
  return window['go']['main']['App']['ActivateTab'](arg1);
}

export function GetTabs() {
  return window['go']['main']['App']['GetTabs']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
