// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateTab(arg1:string):Promise<void>;

export function GetTabs():Promise<Array<main.Tab>>;

export function Greet(arg1:string):Promise<string>;
